### ISSUE TITLE
Server error, status code: 400, error code: 170005, message: App staging failed in the buildpack release phase

### ISSUE THREAD

**Issue by StefH** [cloudfoundry-community/.net-buildpack#43]
```
Connected, dumping recent logs for app *** in org *** / space development as ***...

2015-05-01T14:37:46.78+0200 [API/4]      OUT Created app with guid feb4c4da-7684-4a12-9198-ee9dff27cbed
2015-05-01T14:37:48.57+0200 [API/3]      OUT Updated app with guid feb4c4da-7684-4a12-9198-ee9dff27cbed ({"route"=>"cc52
6f0c-9f0a-41c3-8425-a9126b0831f7"})
2015-05-01T14:38:00.53+0200 [API/3]      OUT Updated app with guid feb4c4da-7684-4a12-9198-ee9dff27cbed ({"state"=>"STAR
TED"})
2015-05-01T14:38:00.64+0200 [STG/22]     OUT -----> Downloaded app package (4.0K)
2015-05-01T14:38:04.27+0200 [STG/0]      ERR     Cloning into '/tmp/buildpacks/.net-buildpack'...
2015-05-01T14:38:04.27+0200 [STG/0]      OUT     -----> Downloading Mono runtime 3.4.0_full from http://ci-labs-buildpack-downloads.s3.amazonaws.com/mono/lucid/x86_64/mono-3.4.0_full.tar.gz (1.3s)
2015-05-01T14:38:04.78+0200 [STG/0]      OUT        expanding Mono to vendor/mono (1.9s)
2015-05-01T14:38:06.98+0200 [STG/0]      OUT -----> Installing Mozilla certificate data to .config/.mono/certs (2.1s)
2015-05-01T14:38:07.08+0200 [STG/0]      OUT -----> Detected console app to be run using '$HOME/vendor/mono/bin/mono --server ***.exe'
2015-05-01T14:38:07.19+0200 [STG/0]      OUT -----> Preparing AppSettingsAutoReconfiguration.exe (0.0s)
2015-05-01T14:38:07.90+0200 [STG/0]      ERR Permission denied - /tmp/staged/app/start.sh
2015-05-01T14:38:07.91+0200 [STG/0]      OUT Staging failed: Release info failed:
2015-05-01T14:38:07.91+0200 [STG/0]      OUT "#<Errno::EACCES: Permission denied - /tmp/staged/app/start.sh>"
2015-05-01T14:38:07.91+0200 [STG/0]      OUT ["/tmp/buildpacks/.net-buildpack/lib/net_buildpack/runtime/mono.rb:119:in `
initialize'",
2015-05-01T14:38:07.91+0200 [STG/0]      OUT  "/tmp/buildpacks/.net-buildpack/lib/net_buildpack/runtime/mono.rb:119:in `
create_start_script'",
2015-05-01T14:38:07.91+0200 [STG/0]      OUT  "/tmp/buildpacks/.net-buildpack/lib/net_buildpack/runtime/mono.rb:75:in `r
elease'",
2015-05-01T14:38:07.91+0200 [STG/0]      OUT  "/tmp/buildpacks/.net-buildpack/lib/net_buildpack/buildpack.rb:133:in `rel
ease'",
2015-05-01T14:38:07.91+0200 [STG/0]      OUT  "/tmp/buildpacks/.net-buildpack/bin/release:27:in `<main>'"]
2015-05-01T14:38:07.91+0200 [STG/0]      OUT Release failed with exception #<IO:0x00000001d032b0>, #<IO:0x00000001d032b0
>
2015-05-01T14:38:08.06+0200 [API/3]      ERR encountered error: App staging failed in the buildpack release phase
```

See also
https://groups.google.com/a/cloudfoundry.org/forum/?utm_medium=email&utm_source=footer#!msg/vcap-dev/Gfpj70hca8A/rJnijUSb-vUJ

**Comment by tburnett80** [comment]
Im also having this same issue. 

Could this be a permissions error from the last cloud foundry release?

```
2015-06-30T09:35:58.84-0500 [API/0]      OUT Created app with guid c2d11b81-119d-4ed6-aa59-066a10e448f2
2015-06-30T09:35:59.15-0500 [API/0]      OUT Updated app with guid c2d11b81-119d-4ed6-aa59-066a10e448f2 ({"route"=>"7ca275a7-4aa6-4037-8b2f-f4852e96637e"})
2015-06-30T09:36:05.02-0500 [DEA/9]      OUT Got staging request for app with id c2d11b81-119d-4ed6-aa59-066a10e448f2
2015-06-30T09:36:06.20-0500 [API/0]      OUT Updated app with guid c2d11b81-119d-4ed6-aa59-066a10e448f2 ({"state"=>"STARTED"})
2015-06-30T09:36:06.38-0500 [STG/9]      OUT -----> Downloaded app package (3.0M)
2015-06-30T09:36:07.40-0500 [STG/0]      ERR     Cloning into '/tmp/buildpacks/.net-buildpack'...
2015-06-30T09:36:12.29-0500 [STG/0]      OUT     -----> Downloading Mono runtime 3.4.0_full from http://ci-labs-buildpack-downloads.s3.amazonaws.com/mono/lucid/x86_64/mono-3.4.0_full.tar.gz (3.7s)
2015-06-30T09:36:14.96-0500 [STG/0]      OUT        expanding Mono to vendor/mono (2.6s)
2015-06-30T09:36:15.25-0500 [STG/0]      OUT -----> Installing Mozilla certificate data to .config/.mono/certs (0.2s)
2015-06-30T09:36:15.33-0500 [STG/0]      OUT -----> Detected console app to be run using '$HOME/vendor/mono/bin/mono --server OutsideSources.API.exe'
2015-06-30T09:36:15.41-0500 [STG/0]      OUT -----> Preparing AppSettingsAutoReconfiguration.exe (0.0s)
2015-06-30T09:36:16.66-0500 [STG/0]      ERR Permission denied - /tmp/staged/app/start.sh
2015-06-30T09:36:16.67-0500 [STG/0]      OUT Staging failed: Release info failed:
2015-06-30T09:36:16.67-0500 [STG/0]      OUT "#<Errno::EACCES: Permission denied - /tmp/staged/app/start.sh>"
2015-06-30T09:36:16.67-0500 [STG/0]      OUT ["/tmp/buildpacks/.net-buildpack/lib/net_buildpack/runtime/mono.rb:119:in `initialize'",
2015-06-30T09:36:16.67-0500 [STG/0]      OUT  "/tmp/buildpacks/.net-buildpack/lib/net_buildpack/runtime/mono.rb:119:in `open'",
2015-06-30T09:36:16.67-0500 [STG/0]      OUT  "/tmp/buildpacks/.net-buildpack/lib/net_buildpack/runtime/mono.rb:119:in `create_start_script'",
2015-06-30T09:36:16.67-0500 [STG/0]      OUT  "/tmp/buildpacks/.net-buildpack/lib/net_buildpack/runtime/mono.rb:75:in `release'",
2015-06-30T09:36:16.67-0500 [STG/0]      OUT  "/tmp/buildpacks/.net-buildpack/lib/net_buildpack/buildpack.rb:133:in `release'",
2015-06-30T09:36:16.67-0500 [STG/0]      OUT  "/tmp/buildpacks/.net-buildpack/bin/release:27:in `<main>'"]
2015-06-30T09:36:16.67-0500 [STG/0]      OUT Release failed with exception #<IO:0x000000017612d0>, #<IO:0x000000017612d0>
2015-06-30T09:36:16.79-0500 [API/0]      ERR encountered error: App staging failed in the buildpack release phase
```

ERR     Cloning into '/tmp/buildpacks/.net-buildpack'...
ERR Permission denied - /tmp/staged/app/start.sh
OUT "Errno::EACCES: Permission denied - /tmp/staged/app/start.sh"

Leads me to believe this could be a permisions issue.

**Comment by tburnett80** [comment]
I think I found the permission issue and submitted a PR
