### ISSUE TITLE
Create NancyFx container

### ISSUE THREAD

**Issue by mrdavidlaing** [cloudfoundry-community/.net-buildpack#9]
Create a container for NancyFx applications based on https://github.com/danhigham/CloudFoundry.Mono

**Comment by mrdavidlaing** [comment]
@danhigham; do you think its necessary for the buildpack to install nginx in front of a NancyFx application?

**Comment by andypiper** [comment]
Is this why I am unable to push https://github.com/squidge/events

```
Preparing to start nancyevents... OK
-----> Downloaded app package (3.7M)
Initialized empty Git repository in /tmp/buildpacks/.net-buildpack/.git/
Compile failed with exception #<RuntimeError: No container can run the application:>
at:
["/tmp/buildpacks/.net-buildpack/lib/net_buildpack/buildpack.rb:299:in `container'",
 "/tmp/buildpacks/.net-buildpack/lib/net_buildpack/buildpack.rb:106:in `compile'",
 "/tmp/buildpacks/.net-buildpack/bin/compile:28:in `<main>'"]
```

**Comment by mrdavidlaing** [comment]
Its likely.  Currently we only have a functioning Console.exe and Procfile containers.

I'd be happy to add a "NancyFX" container to support `squidge/events` - how would you like it to work?

**Comment by andypiper** [comment]
I guess it would be rude to say... "I just want it to work" :-)

right now there isn't a lot of doc in the buildpack in terms of what a dev is expected to push and what is expected to work, whereas the Java buildpack is pretty clear (build your code locally, push, and it detects based on various criteria and inserts runtime and container etc).

This looks like a pretty basic .NET NancyFX app which runs out of MD/Xamarin, albeit once various assemblies are installed via nuget. A simple push "should" be enough (if we are looking to mimic the Java buildpack) to get it up and running.

**Comment by mrdavidlaing** [comment]
@andypiper I had a stab at getting `squidge/events` to work locally and failed.  Specifically, it looks like its missing nuget's `packages.config` that tells NuGet what dependancies to install.  Any idea which packages (and which versions of those packages) should be installed?

It looks like this app is a console app that opens an [HttpListener on localhost:8888-8889](https://github.com/squidge/events/blob/master/Events/Main.cs#L12-L14)

The reason this isn't currently detected and run by the [Console Container](https://github.com/cloudfoundry-community/.net-buildpack/blob/master/lib/net_buildpack/container/console.rb) is that it doesn't have an `Events.exe.config`, which is the Console container's detection criteria.  

Unfortunately, even if we could detect that its a NancyFX console app; the ports its listens on are hardcoded.  If they were part of the config we could "automagically" update them during staging.   

So; the way forward.
1.  I'll add some documentation for the Console container and the AppSettingsAutoConfiguration framework.
2.  I need a "canonical" NancyFX sample app to work with.  Can you suggest one?

**Comment by andypiper** [comment]
Not sure I am able to suggest one, no. I already realised that this would need to be modified to read the port from the environment as you would in any standard app on CF or Heroku - it just looked simple and straightforward enough. I'll cast around for some more example apps.

**Comment by phillip-haydon** [comment]
Just saw your post on the forums. What do you mean by canonical app?

You can run nancy using a console app, but usually need something like nginx to push requests to the app. You can use nancy without a console app using `mono-fastcgi-server4`

http://www.philliphaydon.com/2013/06/setting-up-mono-on-nginx/

http://www.philliphaydon.com/2013/07/setting-up-a-nancyfx-website/

Ports can be configurable. 

There are different reasons for using Self-hosting console app vs a website when it comes to Linux hosting since a console app will allow you to run an Owin host, while you cannot do that when its run on nginx.

**Comment by mrdavidlaing** [comment]
@phillip-haydon, thanks for the pointers.  Concerning:

> What do you mean by canonical app?

The NancyFX hosting tutorials I've seen all show how to deploy super simple "hello world" apps; which I'm sure don't use much of NancyFX.

I'm looking for an existing NancyFX app that I can run to prove that my NancyFX hosting setup on CloudFoundry works.

As an example; to test that my PHP hosting setup works on CloudFoundry I use WordPress; since that is a large and much used PHP application.

Is there something similar for NancyFX?

**Comment by nterry** [comment]
Here you go:

https://github.com/nterry/NancyDemo

There is a simple Nancy self-hosted container. It will even auto-restore
when xbuild is invoked
